version: '2.1'

services:
  kstats:
    container_name: kstats
    image:  devopsansiblede/kstats:latest
    restart: always
    volumes:
      - ${PWD}/.env:/var/www/html/.env
    networks:
      - backbone
      - database
    environment:
      - "APACHE_WORKDIR=/var/www/html/public/"

    ports:
      - 8080:80

  kstats_db:
    container_name: kstats_db
    restart: always
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: kstatskstatskstats
      MYSQL_DATABASE: kstats
      MYSQL_USER: kstats
      MYSQL_PASSWORD: kstatskstatskstats
    networks:
      - database
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql
    networks:
      - database


networks:
  frontend:
    external:
      name: publicwww
  backbone:
    external:
      name: proxy
  database:
    external:
      name: database

